### ISSUE TITLE
Currency Symbol in front of number

### ISSUE THREAD

**Issue by kyoukhana** [HubSpot/odometer#100]
Is is possible to put a dollar sign in front of the number.  If so how.

**Comment by julian-weinert** [comment]
Generally it would be nice to be able to append / prepend strings that don't get animated.
Also animating strings (like on the website) would be amazing also, probably with randomized mixed characters of the string...

**Comment by thesublimeobject** [comment]
I third this.

**Comment by KoltonG** [comment]
+1 for this feature @zackbloom @adamschwartz @andrewreedy

**Comment by adamschwartz** [comment]
This can be solved with just a little CSS:

```
.odometer .odometer-inside:before {
    content: "$";
}
```

[jsFiddle](http://jsfiddle.net/adamschwartz/2254w7vL/)

**Comment by KoltonG** [comment]
@adamschwartz I am having hard time understanding the codebase to see if I can change it. But a simple thought would be that whenever the update is called and it renders the appropriate lenght, couldn't you also call 

```
.odometer .odometer-inside:before {
    content: "$00"
} 
```
but if the length of the new number added another 0 then take off the prefix 0?

```
.odometer .odometer-inside:before {
    content: "$0"
}

**Comment by adamschwartz** [comment]
@KoltonG please see https://github.com/HubSpot/odometer/issues/91#issuecomment-137845693, https://github.com/HubSpot/odometer/issues/81#issuecomment-137844322, and https://github.com/HubSpot/odometer/issues/100#issuecomment-128456783 for responses to the issues brought up here.
