### ISSUE TITLE
Add currency after number

### ISSUE THREAD

**Issue by ckrahenbuhl** [HubSpot/odometer#118]
Hello
this is my first post .
I find to add a currency after the number 
Example : 10000 €

It is possible 

thank you for all reply

**Comment by TropicSapling** [comment]
I have a similar question to this; how to add % after the number? As well as characters if possible

**Comment by adamschwartz** [comment]
Use the workaround in https://github.com/HubSpot/odometer/issues/106 but use `:after` instead of `:before`.

**Comment by TropicSapling** [comment]
@adamschwartz Thanks I'll try that :)

**Comment by adamschwartz** [comment]
Awesome. Let me know how it goes or post your result in #106 to show it off for people! ;)
