### ISSUE TITLE
Does not appear to be compatible with Angularjs

### ISSUE THREAD

**Issue by logstown** [HubSpot/odometer#39]
I added the class to an element to a rendered template created by the `ng-view` directive, and there is no formatting. 

The formatting appears when added to an element outside the `<div ng-view></div>` 

see http://docs.angularjs.org/api/ngRoute.directive:ngView for details.

**Comment by arbaazshaikh919** [comment]
Hello every 1.. i wanna how to link the css and script file for odometer in angulerjs 
please ..any 1..
