### ISSUE TITLE
Adding a left 0 and decimal point

### ISSUE THREAD

**Issue by serversides** [HubSpot/odometer#43]
How to add support for numbers such as £0.84?  I can't seem to add support to allow this.  The number always outputs as £84

**Comment by FelipeMarcos** [comment]
:+1:

**Comment by theother1** [comment]
Any news on the leading zeros? It's an important feature! I don't want my meter to change width all the time.

thanks

**Comment by KoltonG** [comment]
+1 or this feature @zackbloom @adamschwartz @andrewreedy sorry for duplicate question in #105

**Comment by KoltonG** [comment]
Hey Guys, the left 0 issue has been solved here #63 if you look at the last comment :)

**Comment by perragradeen** [comment]
Is this a closed issue?

**Comment by adamschwartz** [comment]
@KoltonG thanks for letting people know about the workaround. But please note that #106 is not a resolution but a workaround.

I’ll be closing this ticket as it should now be considered a duplicate of #106, which at least provides people with a workaround in the meantime. But @perragradeen @serversides and everyone else above, please note that there is still no official support for trailing 0s, currency, or other special formatting as of yet.

Closing as a dup of https://github.com/HubSpot/odometer/issues/106. Please follow this issue there.

**Comment by Lucas-naceri** [comment]
Liked!
