### ISSUE TITLE
Feature request: Don't animate on initialisation, only on change

### ISSUE THREAD

**Issue by laurensnl** [HubSpot/odometer#87]
Would be great if there was an option to disable the animation on load and only animate when the value changes.

**Comment by adamschwartz** [comment]
Can you explain what you mean by this? If you pass in an initial value to odometer, it should not animate on initialization.

See this jsFiddle example: http://jsfiddle.net/adamschwartz/mcmwdyex/

**Comment by laurensnl** [comment]
Oh sorry about that I should have known that this is caused by AngularJS injecting the initial value (as a html attribute) after loading the DOM. By bad! Great script by the way!
